import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Instagram, Linkedin, Mail, Phone, Twitter } from "lucide-react";
import Navbar from "@/components/ui/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prepleet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />

          {children}
          <footer
            style={{
              backgroundColor: "var(--primary)",
              color: "var(--primary-foreground)", // white
            }}
          >
            <div className="container mx-auto px-4 py-12">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                {/* Company Information */}
                <div>
                  <h3 className="text-xl font-bold mb-4">
                    Prep
                    <span style={{ color: "var(--muted)" }}>leet</span>
                  </h3>
                  <p
                    className="mb-4"
                    style={{ color: "var(--primary-foreground)" }}
                  >
                    AI-powered interview preparation platform helping job
                    seekers practice and excel in technical and behavioral
                    interviews.
                  </p>
                  <div className="flex space-x-4">
                    <a
                      href="#"
                      style={{ color: "var(--primary-foreground)" }}
                      className="hover:text-[var(--muted)] transition-colors"
                    >
                      <Instagram size={20} />
                    </a>
                    <a
                      href="#"
                      style={{ color: "var(--primary-foreground)" }}
                      className="hover:text-[var(--muted)] transition-colors"
                    >
                      <Twitter size={20} />
                    </a>
                    <a
                      href="#"
                      style={{ color: "var(--primary-foreground)" }}
                      className="hover:text-[var(--muted)] transition-colors"
                    >
                      <Linkedin size={20} />
                    </a>
                  </div>
                </div>

                {/* Quick Links */}
                <div>
                  <h3 className="text-lg font-semibold mb-4">Quick Links</h3>
                  <ul className="space-y-2">
                    {[
                      ["#home", "Home"],
                      ["#features", "Features"],
                      ["#testimonials", "Testimonials"],
                      ["#", "Pricing"],
                    ].map(([href, label], idx) => (
                      <li key={idx}>
                        <a
                          href={href}
                          style={{ color: "var(--primary-foreground)" }}
                          className="hover:text-[var(--muted)] transition-colors"
                        >
                          {label}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Contact Information */}
                <div>
                  <h3 className="text-lg font-semibold mb-4">Contact Us</h3>
                  <ul className="space-y-3">
                    <li className="flex items-center">
                      <Mail
                        size={16}
                        className="mr-2"
                        style={{ color: "var(--muted)" }}
                      />
                      <a
                        href="mailto:hello@prepleet.com"
                        style={{ color: "var(--primary-foreground)" }}
                        className="hover:text-[var(--muted)] transition-colors"
                      >
                        hello@prepleet.com
                      </a>
                    </li>
                    <li className="flex items-center">
                      <Phone
                        size={16}
                        className="mr-2"
                        style={{ color: "var(--muted)" }}
                      />
                      <a
                        href="tel:+1234567890"
                        style={{ color: "var(--primary-foreground)" }}
                        className="hover:text-[var(--muted)] transition-colors"
                      >
                        +1 (234) 567-890
                      </a>
                    </li>
                  </ul>
                </div>

                {/* Newsletter */}
                <div>
                  <h3 className="text-lg font-semibold mb-4">
                    Get Interview Tips
                  </h3>
                  <p
                    className="mb-4"
                    style={{ color: "var(--primary-foreground)" }}
                  >
                    Subscribe to receive our latest interview strategies and
                    tips.
                  </p>
                  <form className="flex">
                    <input
                      type="email"
                      placeholder="Your email"
                      className="px-4 py-2 rounded-l-md w-full focus:outline-none"
                      style={{
                        border: "1px solid var(--border)",
                        backgroundColor: "var(--background)",
                        color: "var(--foreground)",
                      }}
                    />
                    <button
                      type="submit"
                      className="px-4 py-2 rounded-r-md transition-colors"
                      style={{
                        backgroundColor: "var(--secondary)",
                        color: "var(--secondary-foreground)",
                      }}
                    >
                      Subscribe
                    </button>
                  </form>
                </div>
              </div>

              <div
                className="mt-12 pt-6 text-center"
                style={{
                  borderTop: "1px solid var(--border)",
                  color: "var(--primary-background)",
                }}
              >
                <p>&copy; 2023 Prepleet. All rights reserved.</p>
              </div>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
